name: Automated API Tests

on: [push]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Apidog Tests
        run: |
          npx apidog-cli run \
            --access-token ${{ secrets.APIDOG_ACCESS_TOKEN }} \
           -t 1770829 -e 5984070 -n 1 -r html,cli
